# Generated by Django 6.0.2 on 2026-02-17 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionbatch',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Себестоимость'),
        ),
    ]
