# Generated by Django 6.0.2 on 2026-02-16 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otkcheck',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
    ]
