# Generated by Django 6.0.2 on 2026-02-14 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Линия',
                'verbose_name_plural': 'Линии',
                'db_table': 'lines',
            },
        ),
        migrations.CreateModel(
            name='LineHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('open', 'Открыта'), ('close', 'Закрыта')], max_length=10, verbose_name='Действие')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='production.line')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='line_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'История смены',
                'verbose_name_plural': 'История смен',
                'db_table': 'line_history',
                'ordering': ['-date', '-time'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('created', 'Создан'), ('in_progress', 'В работе'), ('done', 'Готово')], default='created', max_length=20, verbose_name='Статус')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Количество')),
                ('product', models.CharField(max_length=255, verbose_name='Продукт')),
                ('date', models.DateField(verbose_name='Дата')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='production.line')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='recipes.recipe')),
            ],
            options={
                'verbose_name': 'Заказ на производство',
                'verbose_name_plural': 'Заказы',
                'db_table': 'orders',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProductionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=255, verbose_name='Продукт')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Количество')),
                ('date', models.DateField(verbose_name='Дата')),
                ('otk_status', models.CharField(choices=[('pending', 'Ожидает ОТК'), ('accepted', 'Принято'), ('rejected', 'Брак')], default='pending', max_length=20, verbose_name='Статус ОТК')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_batches', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='production.order')),
            ],
            options={
                'verbose_name': 'Партия производства',
                'verbose_name_plural': 'Партии производства',
                'db_table': 'production_batches',
                'ordering': ['-date', '-id'],
            },
        ),
    ]
