# Generated by Django 6.0.2 on 2026-03-18 00:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_productionbatch_cost_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened_at', models.DateTimeField(verbose_name='Начало смены')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Конец смены')),
                ('comment', models.TextField(blank=True, verbose_name='Итоговый комментарий')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to='production.line', verbose_name='Линия')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shifts', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Смена',
                'verbose_name_plural': 'Смены',
                'db_table': 'shifts',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='ShiftNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Заметка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='production.shift', verbose_name='Смена')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift_notes', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Заметка к смене',
                'verbose_name_plural': 'Заметки к сменам',
                'db_table': 'shift_notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['user', '-opened_at'], name='shifts_user_id_653d38_idx'),
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['-opened_at'], name='shifts_opened__590329_idx'),
        ),
    ]
