# Generated by Django 6.0.2 on 2026-03-18 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_shift_shiftnote_shift_shifts_user_id_653d38_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shifts', to='production.line', verbose_name='Линия'),
        ),
    ]
