# Generated by Django 6.0.2 on 2026-03-21 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_alter_shift_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='linehistory',
            name='angle_deg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Угол, °'),
        ),
        migrations.AddField(
            model_name='linehistory',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='linehistory',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Высота'),
        ),
        migrations.AddField(
            model_name='linehistory',
            name='session_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название смены'),
        ),
        migrations.AddField(
            model_name='linehistory',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ширина'),
        ),
        migrations.AlterField(
            model_name='linehistory',
            name='action',
            field=models.CharField(choices=[('open', 'Открыта'), ('close', 'Закрыта'), ('params_update', 'Параметры')], max_length=20, verbose_name='Действие'),
        ),
    ]
