# Generated by Django 6.0.2 on 2026-03-21 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_linehistory_snapshots'),
        ('recipes', '0002_recipe_output_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipe_runs', to='production.line')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipe_runs', to='recipes.recipe')),
            ],
            options={
                'verbose_name': 'Запуск по рецепту',
                'verbose_name_plural': 'Запуски по рецептам',
                'db_table': 'recipe_runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecipeRunBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('label', models.CharField(blank=True, max_length=255, verbose_name='Название')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Количество')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='production.reciperun')),
            ],
            options={
                'verbose_name': 'Партия запуска',
                'verbose_name_plural': 'Партии запуска',
                'db_table': 'recipe_run_batches',
                'ordering': ['index', 'id'],
            },
        ),
    ]
