# Generated by Django 6.0.2 on 2026-03-21 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemistry', '0004_remove_chemistrywriteoff_chemistry_and_more'),
        ('materials', '0003_rawmaterial_min_balance'),
        ('production', '0006_recipe_runs'),
        ('recipes', '0002_recipe_output_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reciperunbatch',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='Сводное количество (опц.)'),
        ),
        migrations.CreateModel(
            name='RecipeRunBatchComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Количество')),
                ('unit', models.CharField(default='кг', max_length=50, verbose_name='Единица')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='production.reciperunbatch')),
                ('chemistry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recipe_run_batch_usages', to='chemistry.chemistrycatalog')),
                ('raw_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recipe_run_batch_usages', to='materials.rawmaterial')),
                ('recipe_component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipe_run_batch_lines', to='recipes.recipecomponent', verbose_name='Строка рецепта')),
            ],
            options={
                'verbose_name': 'Расход по партии',
                'verbose_name_plural': 'Расходы по партиям',
                'db_table': 'recipe_run_batch_components',
                'ordering': ['id'],
            },
        ),
    ]
