# Generated by Django 6.0.2 on 2026-03-21 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0007_recipe_run_batch_components'),
    ]

    operations = [
        migrations.AddField(
            model_name='reciperun',
            name='production_batch',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_recipe_run', to='production.productionbatch', verbose_name='Партия ОТК'),
        ),
    ]
