# Generated by Django 6.0.2 on 2026-03-22 09:45

import django.db.models.deletion
from django.db import migrations, models


def backfill_line_name_snapshots(apps, schema_editor):
    Line = apps.get_model('production', 'Line')
    Order = apps.get_model('production', 'Order')
    RecipeRun = apps.get_model('production', 'RecipeRun')
    LineHistory = apps.get_model('production', 'LineHistory')
    Shift = apps.get_model('production', 'Shift')
    for lid, name in Line.objects.values_list('id', 'name'):
        if not name:
            continue
        Order.objects.filter(line_id=lid).update(line_name_snapshot=name)
        RecipeRun.objects.filter(line_id=lid).update(line_name_snapshot=name)
        LineHistory.objects.filter(line_id=lid).update(line_name_snapshot=name)
        Shift.objects.filter(line_id=lid).update(line_name_snapshot=name)


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0008_recipe_run_production_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='linehistory',
            name='former_line_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Бывший id линии'),
        ),
        migrations.AddField(
            model_name='linehistory',
            name='line_name_snapshot',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Название линии (снимок)'),
        ),
        migrations.AddField(
            model_name='order',
            name='former_line_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Бывший id линии'),
        ),
        migrations.AddField(
            model_name='order',
            name='line_name_snapshot',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Название линии (снимок)'),
        ),
        migrations.AddField(
            model_name='reciperun',
            name='former_line_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Бывший id линии'),
        ),
        migrations.AddField(
            model_name='reciperun',
            name='line_name_snapshot',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Название линии (снимок)'),
        ),
        migrations.AddField(
            model_name='shift',
            name='former_line_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Бывший id линии'),
        ),
        migrations.AddField(
            model_name='shift',
            name='line_name_snapshot',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Название линии (снимок)'),
        ),
        migrations.AlterField(
            model_name='linehistory',
            name='line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='production.line'),
        ),
        migrations.AlterField(
            model_name='order',
            name='line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='production.line'),
        ),
        migrations.AlterField(
            model_name='reciperun',
            name='line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipe_runs', to='production.line'),
        ),
        migrations.RunPython(backfill_line_name_snapshots, migrations.RunPython.noop),
    ]
