# Generated by Django 6.0.2 on 2026-03-22 09:54

import django.db.models.deletion
from django.db import migrations, models


def backfill_recipe_name_snapshots(apps, schema_editor):
    Recipe = apps.get_model('recipes', 'Recipe')
    Order = apps.get_model('production', 'Order')
    RecipeRun = apps.get_model('production', 'RecipeRun')
    for rid, rname in Recipe.objects.values_list('id', 'recipe'):
        snap = (rname or '').strip()
        if not snap:
            continue
        Order.objects.filter(recipe_id=rid).update(recipe_name_snapshot=snap)
        RecipeRun.objects.filter(recipe_id=rid).update(recipe_name_snapshot=snap)


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0009_line_snapshots_and_set_null'),
        ('recipes', '0002_recipe_output_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='former_recipe_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Бывший id рецепта'),
        ),
        migrations.AddField(
            model_name='order',
            name='recipe_name_snapshot',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Наименование рецепта (снимок)'),
        ),
        migrations.AddField(
            model_name='reciperun',
            name='former_recipe_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Бывший id рецепта'),
        ),
        migrations.AddField(
            model_name='reciperun',
            name='recipe_name_snapshot',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Наименование рецепта (снимок)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='recipes.recipe'),
        ),
        migrations.AlterField(
            model_name='reciperun',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipe_runs', to='recipes.recipe'),
        ),
        migrations.RunPython(backfill_recipe_name_snapshots, migrations.RunPython.noop),
    ]
