# Generated by Django 6.0.2 on 2026-03-24 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0013_productionbatch_shift_snapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linehistory',
            name='action',
            field=models.CharField(choices=[('open', 'Открыта'), ('close', 'Закрыта'), ('params_update', 'Параметры'), ('shift_pause', 'Остановка смены'), ('shift_resume', 'Возобновление смены')], max_length=20, verbose_name='Действие'),
        ),
    ]
