# Generated by Django 6.0.2 on 2026-03-24 05:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0014_linehistory_shift_pause_resume'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='Текст')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_shift_complaints', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('mentioned_users', models.ManyToManyField(blank=True, related_name='mentioned_in_shift_complaints', to=settings.AUTH_USER_MODEL, verbose_name='Упомянутые')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='production.shift', verbose_name='Смена')),
            ],
            options={
                'verbose_name': 'Жалоба (смена)',
                'verbose_name_plural': 'Жалобы (смены)',
                'db_table': 'shift_complaints',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='shift_compl_created_9463fc_idx'), models.Index(fields=['author', '-created_at'], name='shift_compl_author__9254e2_idx')],
            },
        ),
    ]
