# Generated by Django 6.0.2 on 2026-03-27 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0016_shift_one_open_per_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='reciperun',
            name='recipe_run_consumption_applied',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Списание по составу замеса применено'),
        ),
    ]
