# Generated by Django 6.0.2 on 2026-04-14 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0020_recipe_run_stock_single_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reciperun',
            name='recipe_run_consumption_applied',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Устарело: раньше помечало списание по замесу (не используется)'),
        ),
    ]
