# Generated by Django

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0025_order_production_request_fields'),
        ('production', '0023_line_code_notes_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionbatch',
            name='client_order',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='production_batches',
                to='sales.order',
                verbose_name='Заявка клиента',
            ),
        ),
    ]
