# Generated by Django — партия с заготовкой цеха

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0004_blankproductionrun_production_batch'),
        ('production', '0024_productionbatch_client_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionbatch',
            name='workshop_blank',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='production_batches',
                to='workshop.workshopblank',
                verbose_name='Заготовка цеха',
            ),
        ),
    ]
