# Generated by Django 4.2.30 on 2026-09-22 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('production', '0025_productionbatch_workshop_blank'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftPhotoReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, default='', verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_photo_reports', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Фотоотчёт по смене',
                'verbose_name_plural': 'Фотоотчёты по сменам',
                'db_table': 'shift_photo_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShiftPhotoReportImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='shift_photo_reports/%Y/%m/', verbose_name='Фото')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='production.shiftphotoreport', verbose_name='Отчёт')),
            ],
            options={
                'verbose_name': 'Фото отчёта по смене',
                'verbose_name_plural': 'Фото отчётов по сменам',
                'db_table': 'shift_photo_report_images',
            },
        ),
        migrations.CreateModel(
            name='ShiftClosing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Наличные')),
                ('card', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Карта')),
                ('expense', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Расход')),
                ('advance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Аванс')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Итого')),
                ('description', models.TextField(blank=True, default='', verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('is_edited', models.BooleanField(default=False, verbose_name='Отредактировано')),
                ('edited_at', models.DateTimeField(blank=True, null=True, verbose_name='Отредактировано в')),
                ('previous_snapshot', models.JSONField(blank=True, null=True, verbose_name='Снимок до правки')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_closings', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Закрытие смены (касса)',
                'verbose_name_plural': 'Закрытия смен (касса)',
                'db_table': 'shift_closings',
                'ordering': ['-created_at'],
            },
        ),
    ]
