# Generated by Django 4.2.30 on 2026-09-26 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_plasticprofile_blank_extra_expenses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('production', '0027_grant_my_shift_access_to_all_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linehistory',
            name='line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='production.line', verbose_name='Линия'),
        ),
        migrations.AlterField(
            model_name='linehistory',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='line_actions', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='productionbatch',
            name='line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_batches', to='production.line', verbose_name='Линия'),
        ),
        migrations.AlterField(
            model_name='productionbatch',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_batches', to=settings.AUTH_USER_MODEL, verbose_name='Оператор'),
        ),
        migrations.AlterField(
            model_name='productionbatch',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='production.order', verbose_name='Заявка на производство'),
        ),
        migrations.AlterField(
            model_name='productionbatch',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_batches', to='recipes.recipe', verbose_name='Рецепт'),
        ),
        migrations.AlterField(
            model_name='reciperun',
            name='line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipe_runs', to='production.line', verbose_name='Линия'),
        ),
        migrations.AlterField(
            model_name='reciperun',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipe_runs', to='recipes.recipe', verbose_name='Рецепт'),
        ),
    ]
