# Generated by Django 6.0.2 on 2026-02-17 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_remove_shipment_client_remove_shipment_order_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Прибыль'),
        ),
    ]
