# Generated by Django 6.0.2 on 2026-03-21 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_sale_profit'),
        ('warehouse', '0002_warehouse_batch_otk_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='packaging',
            field=models.CharField(blank=True, max_length=20, verbose_name='Упаковка'),
        ),
        migrations.AddField(
            model_name='sale',
            name='sale_unit',
            field=models.CharField(blank=True, max_length=50, verbose_name='Единица продажи'),
        ),
        migrations.AddField(
            model_name='sale',
            name='warehouse_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='warehouse.warehousebatch', verbose_name='Партия склада ГП'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='sales.client'),
        ),
    ]
