# Generated by Django 6.0.2 on 2026-03-21 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_sale_warehouse_client_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='packaging',
            field=models.CharField(blank=True, max_length=50, verbose_name='Упаковка (packed/unpacked и т.п.)'),
        ),
    ]
