# Generated by Django 6.0.2 on 2026-04-24 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_orderreservation_sale_line_fulfilled'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='orderreservation',
            new_name='order_reser_order_l_db2c6c_idx',
            old_name='order_res_line_status_idx',
        ),
        migrations.RenameIndex(
            model_name='orderreservation',
            new_name='order_reser_warehou_e65dde_idx',
            old_name='order_res_batch_status_idx',
        ),
        migrations.AlterField(
            model_name='reworkrequest',
            name='quantity_kg',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='Масса входа кг (сырьё)'),
        ),
    ]
