# Generated by Django 6.0.2 on 2026-04-24 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0017_backend_erp_fixes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defectrecord',
            name='source_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID источника (otk, return_line, otk_check_id)'),
        ),
    ]
