# Generated by Django 6.0.2 on 2026-04-26 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0023_defect_status_closed_and_fix_terminal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defectrecord',
            name='original_quantity_pcs',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='Исходно шт (база учёта)'),
        ),
        migrations.AlterField(
            model_name='defectrecord',
            name='quantity_pcs',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='Остаток шт/м (доступно к операциям)'),
        ),
        migrations.AlterField(
            model_name='defectrecord',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('on_stock', 'На складе брака'), ('sent_to_rework', 'Передан на переработку'), ('reworked', 'Переработан'), ('sold', 'Продан'), ('written_off', 'Списан'), ('closed', 'Закрыт')], db_index=True, default='new', max_length=25, verbose_name='Статус'),
        ),
    ]
