# Generated by Django

import django.db.models.deletion
from django.db import migrations, models

import apps.sales.models as sales_models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_recipe_output_quantity_and_more'),
        ('sales', '0024_alter_defectrecord_original_quantity_pcs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='production_length',
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=14, null=True,
                verbose_name='Длина, м/шт (производство)',
            ),
        ),
        migrations.AddField(
            model_name='order',
            name='production_profile',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='client_orders',
                to='recipes.plasticprofile',
                verbose_name='Профиль (производство)',
            ),
        ),
        migrations.AddField(
            model_name='order',
            name='production_quantity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество шт (производство)'),
        ),
        migrations.AddField(
            model_name='order',
            name='request_status',
            field=models.CharField(
                blank=True,
                choices=sales_models.REQUEST_STATUS_CHOICES,
                db_index=True, max_length=20, null=True, verbose_name='Статус (производство)',
            ),
        ),
        migrations.AddField(
            model_name='order',
            name='request_total_meters',
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=16, null=True,
                verbose_name='Всего м (производство, снимок)',
            ),
        ),
        migrations.AddField(
            model_name='order',
            name='resolved_recipe',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='client_orders',
                to='recipes.recipe',
                verbose_name='Рецепт (рассчитан сервером)',
            ),
        ),
        migrations.AddField(
            model_name='order',
            name='resource_check_snapshot',
            field=models.JSONField(
                blank=True, default=sales_models._default_resource_check_snapshot,
                verbose_name='Снимок проверки ресурсов',
            ),
        ),
    ]
