# Generated by Django 4.2.30 on 2026-05-17 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0011_gp_pack_unit_warehouse_batch_and_sale_line'),
        ('sales', '0028_client_type_and_company_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleline',
            name='gp_pack_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_lines', to='warehouse.gppackunit', verbose_name='Упаковка GP (продажа по gp_package_id)'),
        ),
    ]
