# Generated by Django 6.0.2 on 2026-08-10 03:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoamDensityGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код')),
                ('min_kg_m3', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Плотность мин, кг/м³')),
                ('max_kg_m3', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Плотность макс, кг/м³')),
            ],
            options={
                'verbose_name': 'Плотность (грейд)',
                'verbose_name_plural': 'Справочник плотностей',
                'db_table': 'foam_density_grades',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='FoamRawLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_number', models.CharField(max_length=50, unique=True, verbose_name='Номер лота')),
                ('material_name', models.CharField(max_length=255, verbose_name='Материал')),
                ('supplier', models.CharField(blank=True, default='', max_length=255, verbose_name='Поставщик')),
                ('bag_weight_kg', models.DecimalField(decimal_places=1, max_digits=12, verbose_name='Вес мешка, кг')),
                ('received_kg', models.DecimalField(decimal_places=1, max_digits=12, verbose_name='Приход, кг')),
                ('remaining_kg', models.DecimalField(decimal_places=1, max_digits=12, verbose_name='Остаток, кг')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата прихода')),
            ],
            options={
                'verbose_name': 'Лот сырья (пенопласт)',
                'verbose_name_plural': 'Лоты сырья (пенопласт)',
                'db_table': 'foam_raw_lots',
                'ordering': ['-received_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FoamSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=255, verbose_name='Клиент')),
                ('sale_date', models.DateField(verbose_name='Дата продажи')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Сумма')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Оплачено')),
                ('payment_status', models.CharField(choices=[('paid', 'Оплачено'), ('partial', 'Частично оплачено'), ('debt', 'Долг')], max_length=20, verbose_name='Статус оплаты')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Продажа (пенопласт)',
                'verbose_name_plural': 'Продажи (пенопласт)',
                'db_table': 'foam_sales',
                'ordering': ['-sale_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FoamGpOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('production_intake', 'Поступление с производства'), ('sale', 'Продажа'), ('defect', 'Брак'), ('return', 'Возврат'), ('cut_in', 'Нарезка листов — получено'), ('cut_out', 'Нарезка листов — списан куб')], max_length=20, verbose_name='Тип операции')),
                ('output_format', models.CharField(choices=[('cube', 'Куб'), ('sheet', 'Лист'), ('granule', 'Гранулы на продажу')], max_length=20, verbose_name='Формат')),
                ('thickness_cm', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Толщина, см')),
                ('qty', models.DecimalField(decimal_places=1, max_digits=12, verbose_name='Кол-во (со знаком)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Когда')),
                ('ref', models.CharField(blank=True, default='', max_length=100, verbose_name='Ссылка на документ')),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gp_operations', to='foam.foamdensitygrade')),
            ],
            options={
                'verbose_name': 'Движение склада ГП (пенопласт)',
                'verbose_name_plural': 'Движения склада ГП (пенопласт)',
                'db_table': 'foam_gp_operations',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FoamGpStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_format', models.CharField(choices=[('cube', 'Куб'), ('sheet', 'Лист'), ('granule', 'Гранулы на продажу')], max_length=20, verbose_name='Формат')),
                ('thickness_cm', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Толщина, см')),
                ('qty', models.DecimalField(decimal_places=1, default=0, max_digits=12, verbose_name='Остаток')),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gp_stock_rows', to='foam.foamdensitygrade')),
            ],
            options={
                'verbose_name': 'Остаток склада ГП (пенопласт)',
                'verbose_name_plural': 'Остатки склада ГП (пенопласт)',
                'db_table': 'foam_gp_stock',
                'ordering': ['output_format', 'grade_id', 'thickness_cm'],
            },
        ),
        migrations.CreateModel(
            name='FoamProductionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_kg', models.DecimalField(decimal_places=1, max_digits=12, verbose_name='Расход сырья, кг')),
                ('output_format', models.CharField(choices=[('cube', 'Куб'), ('sheet', 'Лист'), ('granule', 'Гранулы на продажу')], max_length=20, verbose_name='Формат выхода')),
                ('output_qty', models.DecimalField(decimal_places=1, max_digits=12, verbose_name='Выход')),
                ('produced_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата выпуска')),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_runs', to='foam.foamdensitygrade')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='foam_production_runs', to=settings.AUTH_USER_MODEL)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_runs', to='foam.foamrawlot')),
            ],
            options={
                'verbose_name': 'Выпуск производства (пенопласт)',
                'verbose_name_plural': 'Выпуски производства (пенопласт)',
                'db_table': 'foam_production_runs',
                'ordering': ['-produced_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FoamSaleLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=1, max_digits=12, verbose_name='Кол-во')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена за ед.')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='foam.foamsale')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_lines', to='foam.foamgpstock')),
            ],
            options={
                'verbose_name': 'Строка продажи (пенопласт)',
                'verbose_name_plural': 'Строки продаж (пенопласт)',
                'db_table': 'foam_sale_lines',
            },
        ),
    ]
