# Generated by Django 4.2.30 on 2026-09-21 13:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('foam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foamrawlot',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Цена за единицу, сом'),
        ),
        migrations.AlterField(
            model_name='foamrawlot',
            name='received_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата прихода'),
        ),
    ]
