# Generated by Django 4.2.30 on 2026-09-26 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0030_sale_checkout_payment_fields'),
        ('foam', '0002_foamrawlot_unit_price_alter_foamrawlot_received_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='foamsale',
            name='client_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='foam_sales', to='sales.client', verbose_name='Клиент (справочник)'),
        ),
        migrations.AddField(
            model_name='foamsale',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Скидка на чек'),
        ),
    ]
