# Generated by Django 4.2.30 on 2026-09-26 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foam', '0003_foamsale_client_account_foamsale_discount_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foamgpstock',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gp_stock_rows', to='foam.foamdensitygrade', verbose_name='Плотность (грейд)'),
        ),
        migrations.AlterField(
            model_name='foamproductionrun',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_runs', to='foam.foamdensitygrade', verbose_name='Плотность (грейд)'),
        ),
        migrations.AlterField(
            model_name='foamproductionrun',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_runs', to='foam.foamrawlot', verbose_name='Лот сырья'),
        ),
        migrations.AlterField(
            model_name='foamproductionrun',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='foam_production_runs', to=settings.AUTH_USER_MODEL, verbose_name='Оператор'),
        ),
    ]
