# Generated by Django 6.0.2 on 2026-04-09 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_access_full_copy_from_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraccess',
            options={'verbose_name': 'Ключ доступа (вкладка)', 'verbose_name_plural': 'Ключи доступа (вкладки)'},
        ),
    ]
