# Generated by Django 6.0.2 on 2026-02-14 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('unit', models.CharField(default='кг', max_length=50, verbose_name='Единица')),
            ],
            options={
                'verbose_name': 'Сырьё',
                'verbose_name_plural': 'Справочник сырья',
                'db_table': 'raw_materials',
            },
        ),
        migrations.CreateModel(
            name='MaterialWriteoff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Количество')),
                ('unit', models.CharField(default='кг', max_length=50, verbose_name='Единица')),
                ('reason', models.CharField(blank=True, max_length=100, verbose_name='Причина')),
                ('reference_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID связи')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='writeoffs', to='materials.rawmaterial')),
            ],
            options={
                'verbose_name': 'Списание сырья',
                'db_table': 'material_writeoffs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Incoming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Количество')),
                ('unit', models.CharField(default='кг', max_length=50, verbose_name='Единица')),
                ('batch', models.CharField(blank=True, max_length=100, verbose_name='Партия')),
                ('supplier', models.CharField(blank=True, max_length=255, verbose_name='Поставщик')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incomings', to='materials.rawmaterial')),
            ],
            options={
                'verbose_name': 'Приход',
                'verbose_name_plural': 'Приходы сырья',
                'db_table': 'incoming',
                'ordering': ['-date', '-id'],
            },
        ),
    ]
