# Generated by Django 6.0.2 on 2026-02-17 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incoming',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Цена за единицу'),
        ),
    ]
