# Generated by Django 6.0.2 on 2026-03-21 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_incoming_price_per_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterial',
            name='min_balance',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='Мин. остаток (порог)'),
        ),
    ]
