# Generated by Django 6.0.2 on 2026-04-14 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0008_rawmaterial_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materialbatch',
            options={'ordering': ['-received_at', '-created_at', '-id'], 'verbose_name': 'Партия сырья', 'verbose_name_plural': 'Партии прихода сырья'},
        ),
        migrations.AlterField(
            model_name='materialbatch',
            name='unit',
            field=models.CharField(default='kg', max_length=50, verbose_name='Единица хранения количества'),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='unit',
            field=models.CharField(default='kg', max_length=50, verbose_name='Единица'),
        ),
    ]
