# Generated by Django 6.0.2 on 2026-02-14 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('production', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OtkCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='Принято')),
                ('rejected', models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='Брак')),
                ('reject_reason', models.TextField(blank=True, verbose_name='Причина брака')),
                ('checked_date', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otk_checks', to='production.productionbatch')),
                ('inspector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='otk_checks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Проверка ОТК',
                'verbose_name_plural': 'Проверки ОТК',
                'db_table': 'otk_checks',
                'ordering': ['-checked_date'],
            },
        ),
    ]
