# Generated by Django 4.2.30 on 2026-05-14 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chemistry', '0007_alter_chemistryrecipe_options_and_more'),
        ('recipes', '0008_alter_recipecomponent_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkshopBlank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('recipe_kg_per_barrel', models.DecimalField(decimal_places=6, max_digits=14, verbose_name='Кг в одной бочке по рецепту')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Комментарий')),
                ('chemistry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workshop_blanks', to='chemistry.chemistrycatalog', verbose_name='Связь с хим. полуфабрикатом')),
            ],
            options={
                'verbose_name': 'Заготовка (цех)',
                'verbose_name_plural': 'Заготовки (цех)',
                'db_table': 'workshop_blanks',
            },
        ),
        migrations.CreateModel(
            name='WorkshopPreparedState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barrels', models.PositiveIntegerField(default=0, verbose_name='Бочек')),
                ('extra_kg', models.DecimalField(decimal_places=6, default=0, max_digits=14, verbose_name='Дробный остаток, кг')),
                ('blank', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prepared_state', to='workshop.workshopblank', verbose_name='Заготовка')),
            ],
            options={
                'verbose_name': 'Остаток заготовки на цеху',
                'verbose_name_plural': 'Остатки заготовок на цеху',
                'db_table': 'workshop_prepared_state',
            },
        ),
        migrations.CreateModel(
            name='BlankProductionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('blank_name_snapshot', models.CharField(max_length=255, verbose_name='Наименование заготовки (снимок)')),
                ('product_name_snapshot', models.CharField(max_length=255, verbose_name='Наименование ГП (снимок)')),
                ('blank_total_kg', models.DecimalField(decimal_places=6, max_digits=14, verbose_name='Общая масса заготовки по данным оператора')),
                ('blank_used_in_production_kg', models.DecimalField(decimal_places=6, max_digits=14, verbose_name='Запуск партии с цеха, кг')),
                ('vat_max_kg_demo', models.DecimalField(decimal_places=6, max_digits=14, verbose_name='Для демо: лимит веса VAT, кг')),
                ('weight_kg_per_piece', models.DecimalField(decimal_places=6, max_digits=14, verbose_name='Вес одной шт, кг')),
                ('defect_kg', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True, verbose_name='Брак ОТК, кг')),
                ('good_kg', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True, verbose_name='Годный после ОТК, кг')),
                ('good_pieces', models.IntegerField(blank=True, null=True, verbose_name='Шт после ОТК (расчёт)')),
                ('otk_recorded_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата записи ОТК')),
                ('gp_accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата приёмки ГП')),
                ('gp_accepted_pieces', models.IntegerField(blank=True, null=True, verbose_name='Принято штук ГП')),
                ('gp_accepted_kg', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True, verbose_name='Принято кг на ГП')),
                ('gp_machine_remainder_kg', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True, verbose_name='Остаток на машине, кг (возврат на цех)')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('in_production', 'В производстве'), ('otk_done', 'ОТК выполнен'), ('gp_accepted', 'Принято на склад ГП')], default='in_production', max_length=20)),
                ('blank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_runs', to='workshop.workshopblank', verbose_name='Заготовка')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workshop_production_runs', to='recipes.plasticprofile', verbose_name='Готовая продукция (SKU)')),
            ],
            options={
                'verbose_name': 'Партия производства по заготовке',
                'verbose_name_plural': 'Партии производства по заготовкам',
                'db_table': 'workshop_blank_production_runs',
                'ordering': ('-created_at', '-pk'),
            },
        ),
    ]
