# Generated by Django 4.2.30 on 2026-05-14 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0009_alter_materialbatch_options_alter_materialbatch_unit_and_more'),
        ('workshop', '0001_workshop_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkshopBlankCompositionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_kg', models.DecimalField(decimal_places=6, max_digits=14, verbose_name='Количество, кг')),
                ('blank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='composition_lines', to='workshop.workshopblank', verbose_name='Заготовка')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workshop_blank_composition_lines', to='materials.rawmaterial', verbose_name='Сырьё')),
            ],
            options={
                'verbose_name': 'Строка состава заготовки',
                'verbose_name_plural': 'Состав заготовок (цех)',
                'db_table': 'workshop_blank_composition_lines',
            },
        ),
        migrations.AddConstraint(
            model_name='workshopblankcompositionline',
            constraint=models.UniqueConstraint(fields=('blank', 'raw_material'), name='workshop_blank_comp_unique_rm'),
        ),
    ]
