# Generated by Django — workshop blank profile filter + is_active

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_plastic_profile_weight_and_optional_code'),
        ('workshop', '0002_blank_composition_and_blanks_api'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopblank',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AddField(
            model_name='workshopblank',
            name='plastic_profile',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='workshop_blanks',
                to='recipes.plasticprofile',
                verbose_name='Профиль ГП (если задан — только для этого профиля)',
            ),
        ),
    ]
