# Generated by Django — связь партии цеха с ProductionBatch

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0024_productionbatch_client_order'),
        ('workshop', '0003_workshopblank_profile_and_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='blankproductionrun',
            name='production_batch',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='blank_production_runs',
                to='production.productionbatch',
                verbose_name='Партия производства (линия)',
            ),
        ),
    ]
