# Generated by Django 6.0.2 on 2026-05-17 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_plastic_profile_weight_and_optional_code'),
        ('workshop', '0004_blankproductionrun_production_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshopblank',
            name='plastic_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workshop_blanks', to='recipes.plasticprofile', verbose_name='Профиль ГП (если задан — заготовка только для этого профиля)'),
        ),
    ]
