# Generated by Django 4.2.30 on 2026-09-26 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0009_otk_account_v2'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshoppreparedstate',
            name='defect_kg',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=14, verbose_name='Брак в остатке, кг'),
        ),
    ]
