# Generated by Django 6.0.2 on 2026-02-14 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=255, verbose_name='Продукт')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Количество')),
                ('status', models.CharField(choices=[('available', 'Доступна'), ('reserved', 'Зарезервирована'), ('shipped', 'Отгружена')], default='available', max_length=20, verbose_name='Статус')),
                ('date', models.DateField(verbose_name='Дата')),
                ('source_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_batches', to='production.productionbatch')),
            ],
            options={
                'verbose_name': 'Партия ГП',
                'verbose_name_plural': 'Партии ГП на складе',
                'db_table': 'warehouse_batches',
                'ordering': ['-date', '-id'],
            },
        ),
    ]
