# Generated by Django 6.0.2 on 2026-03-21 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehousebatch',
            name='otk_accepted',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='ОТК принято'),
        ),
        migrations.AddField(
            model_name='warehousebatch',
            name='otk_checked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата проверки ОТК'),
        ),
        migrations.AddField(
            model_name='warehousebatch',
            name='otk_comment',
            field=models.TextField(blank=True, verbose_name='Комментарий ОТК'),
        ),
        migrations.AddField(
            model_name='warehousebatch',
            name='otk_defect',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='ОТК брак'),
        ),
        migrations.AddField(
            model_name='warehousebatch',
            name='otk_defect_reason',
            field=models.TextField(blank=True, verbose_name='Причина брака'),
        ),
        migrations.AddField(
            model_name='warehousebatch',
            name='otk_inspector_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Контролёр ОТК'),
        ),
        migrations.AddField(
            model_name='warehousebatch',
            name='otk_status',
            field=models.CharField(blank=True, max_length=20, verbose_name='Статус ОТК (снимок)'),
        ),
        migrations.AddField(
            model_name='warehousebatch',
            name='package_total_meters',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='М в упаковке'),
        ),
        migrations.AddField(
            model_name='warehousebatch',
            name='packages_count',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='Число упаковок'),
        ),
        migrations.AddField(
            model_name='warehousebatch',
            name='pieces_per_package',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='Штук в упаковке'),
        ),
        migrations.AddField(
            model_name='warehousebatch',
            name='unit_meters',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='М/ед.'),
        ),
    ]
