# Generated by Django 6.0.2 on 2026-05-03 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0008_warehousebatch_stock_bucket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehousebatch',
            name='stock_bucket',
            field=models.CharField(choices=[('standard', 'Основной склад ГП'), ('reworked', 'Переделанные')], db_index=True, default='standard', max_length=20, verbose_name='Сегмент склада'),
        ),
    ]
