# Generated by Django 4.2.30 on 2026-05-17 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workshop', '0004_blankproductionrun_production_batch'),
        ('recipes', '0009_plastic_profile_weight_and_optional_code'),
        ('warehouse', '0009_alter_warehousebatch_stock_bucket'),
    ]

    operations = [
        migrations.CreateModel(
            name='GpPackOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('pallet', 'Поддон'), ('box', 'Короб'), ('other', 'Иное')], max_length=16, verbose_name='Тип')),
                ('label', models.CharField(blank=True, default='', max_length=255, verbose_name='Метка')),
                ('split_mode', models.CharField(choices=[('single', 'Одна упаковка'), ('uniform', 'Одинаковые упаковки'), ('custom', 'Разный состав')], max_length=16, verbose_name='Режим разбиения')),
                ('total_pieces', models.PositiveIntegerField(verbose_name='Всего штук в операции')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('client_request_id', models.CharField(blank=True, default=None, max_length=64, null=True, unique=True, verbose_name='Идемпотентность (клиент)')),
                ('blank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gp_pack_operations', to='workshop.workshopblank', verbose_name='Заготовка')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gp_pack_operations', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gp_pack_operations', to='recipes.plasticprofile', verbose_name='ГП (SKU)')),
            ],
            options={
                'verbose_name': 'Операция упаковки ГП',
                'verbose_name_plural': 'Операции упаковки ГП',
                'db_table': 'warehouse_gp_pack_operations',
                'ordering': ('-created_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='GpPackUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(verbose_name='Порядок')),
                ('pieces', models.PositiveIntegerField(verbose_name='Штук в упаковке')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='warehouse.gppackoperation', verbose_name='Операция')),
            ],
            options={
                'verbose_name': 'Единица упаковки ГП',
                'verbose_name_plural': 'Единицы упаковки ГП',
                'db_table': 'warehouse_gp_pack_units',
                'ordering': ('operation_id', 'sequence', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='GpPackRunAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pieces', models.PositiveIntegerField(verbose_name='Штук')),
                ('kg', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True, verbose_name='Кг (снимок)')),
                ('blank_production_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gp_pack_allocations', to='workshop.blankproductionrun', verbose_name='Партия (приёмка ГП)')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_allocations', to='warehouse.gppackoperation', verbose_name='Операция')),
            ],
            options={
                'verbose_name': 'Списание упаковки с приёмки',
                'verbose_name_plural': 'Списания упаковки с приёмок',
                'db_table': 'warehouse_gp_pack_run_allocations',
            },
        ),
        migrations.AddConstraint(
            model_name='gppackunit',
            constraint=models.UniqueConstraint(fields=('operation', 'sequence'), name='uniq_gp_pack_unit_op_seq'),
        ),
        migrations.AddIndex(
            model_name='gppackrunallocation',
            index=models.Index(fields=['blank_production_run'], name='warehouse_g_blank_p_9a4902_idx'),
        ),
    ]
