# Generated by Django 4.2.30 on 2026-05-17 14:10

from decimal import Decimal

from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone


def backfill_gp_pack_unit_warehouse_batches(apps, schema_editor):
    GpPackUnit = apps.get_model('warehouse', 'GpPackUnit')
    GpPackOperation = apps.get_model('warehouse', 'GpPackOperation')
    WarehouseBatch = apps.get_model('warehouse', 'WarehouseBatch')
    PlasticProfile = apps.get_model('recipes', 'PlasticProfile')

    for unit in GpPackUnit.objects.all().iterator():
        if unit.warehouse_batch_id:
            continue
        try:
            op = GpPackOperation.objects.get(pk=unit.operation_id)
        except GpPackOperation.DoesNotExist:
            continue
        prof = PlasticProfile.objects.filter(pk=op.product_id).first() if op.product_id else None
        name = ((getattr(prof, 'name', None) or '').strip()[:255]) if prof else '—'
        pcs = int(getattr(unit, 'pieces', 0) or 0)
        if pcs <= 0:
            continue
        d = timezone.now().date()
        ppp = Decimal(str(pcs))
        wb = WarehouseBatch.objects.create(
            profile_id=op.product_id,
            product=name,
            length_per_piece=None,
            total_meters=None,
            quantity=ppp,
            cost_per_piece=Decimal('0'),
            cost_per_meter=Decimal('0'),
            status='available',
            date=d,
            source_batch_id=None,
            inventory_form='packed',
            unit_meters=None,
            package_total_meters=None,
            pieces_per_package=ppp,
            packages_count=Decimal('1'),
            quality='good',
            stock_bucket='standard',
        )
        unit.warehouse_batch_id = wb.pk
        unit.save(update_fields=['warehouse_batch_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0010_gp_pack_operations'),
    ]

    operations = [
        migrations.AddField(
            model_name='gppackunit',
            name='warehouse_batch',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='gp_pack_units',
                to='warehouse.warehousebatch',
                verbose_name='Партия склада ГП (1 упаковка = 1 строка)',
            ),
        ),
        migrations.RunPython(backfill_gp_pack_unit_warehouse_batches, migrations.RunPython.noop),
    ]
