# Generated by Django 6.0.2 on 2026-05-17 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0012_warehousebatch_blank_production_run'),
        ('workshop', '0005_alter_workshopblank_plastic_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehousebatch',
            name='blank_production_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_gp_acceptance_batches', to='workshop.blankproductionrun', verbose_name='Приёмка ГП (неупакованная строка по приёмке)'),
        ),
    ]
