# Generated by Django 6.0.2 on 2026-02-14 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('contact', models.CharField(blank=True, max_length=255, verbose_name='Контакт')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('inn', models.CharField(blank=True, max_length=20, verbose_name='ИНН')),
                ('address', models.TextField(blank=True, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'db_table': 'clients',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=100, verbose_name='Номер заказа')),
                ('product', models.CharField(max_length=255, verbose_name='Продукт')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Количество')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Цена')),
                ('date', models.DateField(verbose_name='Дата')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='sales.client')),
            ],
            options={
                'verbose_name': 'Продажа',
                'verbose_name_plural': 'Продажи',
                'db_table': 'sales',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=100, verbose_name='Номер заказа')),
                ('product', models.CharField(max_length=255, verbose_name='Продукт')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Количество')),
                ('status', models.CharField(choices=[('pending', 'К отгрузке'), ('shipped', 'Отгружено'), ('delivered', 'Доставлено')], default='pending', max_length=20, verbose_name='Статус')),
                ('shipment_number', models.CharField(blank=True, max_length=100, verbose_name='Номер отгрузки')),
                ('shipment_date', models.DateField(blank=True, null=True, verbose_name='Дата отгрузки')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='Дата доставки')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='sales.client')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='sales.sale')),
            ],
            options={
                'verbose_name': 'Отгрузка',
                'verbose_name_plural': 'Отгрузки',
                'db_table': 'shipments',
                'ordering': ['-id'],
            },
        ),
    ]
