# Generated by Django 6.0.2 on 2026-02-17 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_add_comment_to_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='client',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='order_number',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='product',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='shipment_number',
        ),
        migrations.AddField(
            model_name='shipment',
            name='address',
            field=models.TextField(blank=True, verbose_name='Адрес доставки'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
    ]
