# Generated by Django 4.2.30 on 2026-09-24 04:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0001_other_expenses'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Название')),
                ('kind', models.CharField(choices=[('expense', 'Расход'), ('income', 'Приход')], default='expense', max_length=10, verbose_name='Тип')),
                ('is_payroll', models.BooleanField(default=False, verbose_name='Это зарплата')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('sort_order', models.PositiveSmallIntegerField(default=100, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Категория расхода',
                'verbose_name_plural': 'Категории расходов',
                'db_table': 'analytics_expense_categories',
                'ordering': ['kind', 'sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='analyticsotherexpense',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='analyticsotherexpense',
            name='kind',
            field=models.CharField(choices=[('expense', 'Расход'), ('income', 'Приход')], db_index=True, default='expense', max_length=10, verbose_name='Тип'),
        ),
        migrations.AddField(
            model_name='analyticsotherexpense',
            name='period_key',
            field=models.CharField(blank=True, default='', max_length=7, verbose_name='Месяц регулярной записи (YYYY-MM)'),
        ),
        migrations.AddField(
            model_name='analyticsotherexpense',
            name='product_line',
            field=models.CharField(choices=[('general', 'Общий'), ('profile', 'Пластиковый профиль'), ('foam', 'Пенополистирол')], default='general', max_length=10, verbose_name='Товарная линия'),
        ),
        migrations.AddField(
            model_name='analyticsotherexpense',
            name='recurring',
            field=models.BooleanField(default=False, verbose_name='Повторять ежемесячно'),
        ),
        migrations.AddField(
            model_name='analyticsotherexpense',
            name='recurring_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occurrences', to='analytics.analyticsotherexpense', verbose_name='Шаблон регулярного расхода'),
        ),
        migrations.AddField(
            model_name='analyticsotherexpense',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Изменено'),
        ),
        migrations.AddField(
            model_name='analyticsotherexpense',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_other_expenses_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='analyticsotherexpense',
            index=models.Index(fields=['kind', 'status', 'date'], name='analytics_o_kind_a0c18f_idx'),
        ),
        migrations.AddConstraint(
            model_name='analyticsotherexpense',
            constraint=models.UniqueConstraint(condition=models.Q(('recurring_source__isnull', False)), fields=('recurring_source', 'period_key'), name='uniq_recurring_occurrence_per_month'),
        ),
        migrations.AddConstraint(
            model_name='analyticsexpensecategory',
            constraint=models.UniqueConstraint(fields=('kind', 'name'), name='uniq_expense_category_kind_name'),
        ),
        migrations.AddField(
            model_name='analyticsotherexpense',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='analytics.analyticsexpensecategory', verbose_name='Категория'),
        ),
    ]
