# Generated by Django 6.0.2 on 2026-02-14 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChemistryCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('unit', models.CharField(default='кг', max_length=50, verbose_name='Единица')),
            ],
            options={
                'verbose_name': 'Хим. элемент',
                'verbose_name_plural': 'Справочник хим. элементов',
                'db_table': 'chemistry_catalog',
            },
        ),
        migrations.CreateModel(
            name='ChemistryStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='Остаток')),
                ('unit', models.CharField(default='кг', max_length=50, verbose_name='Единица')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chemistry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='chemistry.chemistrycatalog')),
            ],
            options={
                'verbose_name': 'Остаток хим. элемента',
                'verbose_name_plural': 'Остатки хим. элементов',
                'db_table': 'chemistry_stock',
            },
        ),
        migrations.CreateModel(
            name='ChemistryTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('status', models.CharField(choices=[('pending', 'К выполнению'), ('in_progress', 'В работе'), ('done', 'Выполнено')], default='pending', max_length=20, verbose_name='Статус')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Срок')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Количество')),
                ('unit', models.CharField(default='кг', max_length=50, verbose_name='Единица')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chemistry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='chemistry.chemistrycatalog')),
            ],
            options={
                'verbose_name': 'Задание по химии',
                'verbose_name_plural': 'Задания по химии',
                'db_table': 'chemistry_tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChemistryTaskElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Количество')),
                ('unit', models.CharField(default='кг', max_length=50, verbose_name='Единица')),
                ('chemistry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_elements', to='chemistry.chemistrycatalog')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='chemistry.chemistrytask')),
            ],
            options={
                'verbose_name': 'Элемент задания',
                'verbose_name_plural': 'Элементы заданий',
                'db_table': 'chemistry_task_elements',
            },
        ),
        migrations.CreateModel(
            name='ChemistryComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_per_unit', models.DecimalField(decimal_places=6, max_digits=14, verbose_name='Количество на единицу')),
                ('chemistry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compositions', to='chemistry.chemistrycatalog')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chemistry_compositions', to='materials.rawmaterial')),
            ],
            options={
                'verbose_name': 'Состав хим. элемента',
                'verbose_name_plural': 'Составы',
                'db_table': 'chemistry_composition',
                'unique_together': {('chemistry', 'raw_material')},
            },
        ),
    ]
