# Generated by Django 6.0.2 on 2026-02-15 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemistry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemistrystock',
            name='last_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='chemistry.chemistrytask'),
        ),
    ]
