# Generated by Django 6.0.2 on 2026-02-17 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemistry', '0002_add_chemistrystock_last_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chemistrystock',
            name='last_task',
        ),
        migrations.CreateModel(
            name='ChemistryIncoming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Количество')),
                ('unit', models.CharField(default='кг', max_length=50, verbose_name='Единица')),
                ('price_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Цена за единицу')),
                ('supplier', models.CharField(blank=True, max_length=255, verbose_name='Поставщик')),
                ('chemistry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incomings', to='chemistry.chemistrycatalog')),
            ],
            options={
                'verbose_name': 'Приход химии',
                'verbose_name_plural': 'Приходы химии',
                'db_table': 'chemistry_incoming',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ChemistryWriteoff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Количество')),
                ('unit', models.CharField(default='кг', max_length=50, verbose_name='Единица')),
                ('reason', models.CharField(blank=True, max_length=100, verbose_name='Причина')),
                ('reference_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID связи')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chemistry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='writeoffs', to='chemistry.chemistrycatalog')),
            ],
            options={
                'verbose_name': 'Списание химии',
                'db_table': 'chemistry_writeoffs',
                'ordering': ['-created_at'],
            },
        ),
    ]
