# Generated by Django 6.0.2 on 2026-02-17 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemistry', '0003_remove_chemistrystock_last_task_chemistryincoming_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chemistrywriteoff',
            name='chemistry',
        ),
        migrations.AddField(
            model_name='chemistrystock',
            name='last_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='chemistry.chemistrytask'),
        ),
        migrations.DeleteModel(
            name='ChemistryIncoming',
        ),
        migrations.DeleteModel(
            name='ChemistryWriteoff',
        ),
    ]
