# Generated by Django 6.0.2 on 2026-04-14 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemistry', '0006_chemistry_catalog_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chemistryrecipe',
            options={'verbose_name': 'Строка состава химии', 'verbose_name_plural': 'Состав химии (рецепт)'},
        ),
        migrations.AlterField(
            model_name='chemistrycatalog',
            name='unit',
            field=models.CharField(default='kg', max_length=50, verbose_name='Единица'),
        ),
        migrations.AlterField(
            model_name='chemistryrecipe',
            name='quantity_per_unit',
            field=models.DecimalField(decimal_places=6, max_digits=14, verbose_name='Количество на 1 кг химии'),
        ),
        migrations.AlterField(
            model_name='chemistrytask',
            name='unit',
            field=models.CharField(default='kg', max_length=50, verbose_name='Единица'),
        ),
        migrations.AlterField(
            model_name='chemistrytaskelement',
            name='unit',
            field=models.CharField(default='kg', max_length=50, verbose_name='Единица'),
        ),
    ]
