# Generated by Django 4.2.30 on 2026-09-26 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chemistry', '0007_alter_chemistryrecipe_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemistrytask',
            name='chemistry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='chemistry.chemistrycatalog', verbose_name='Химия'),
        ),
    ]
