# Generated by Django 6.0.2 on 2026-02-14 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chemistry', '0001_initial'),
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.CharField(max_length=255, verbose_name='Наименование рецепта')),
                ('product', models.CharField(max_length=255, verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
                'db_table': 'recipes',
            },
        ),
        migrations.CreateModel(
            name='RecipeComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('raw', 'Сырьё'), ('chem', 'Хим. элемент')], max_length=10, verbose_name='Тип')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Количество')),
                ('unit', models.CharField(default='кг', max_length=50, verbose_name='Единица')),
                ('chemistry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipe_components', to='chemistry.chemistrycatalog')),
                ('raw_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipe_components', to='materials.rawmaterial')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='recipes.recipe')),
            ],
            options={
                'verbose_name': 'Компонент рецепта',
                'verbose_name_plural': 'Компоненты рецептов',
                'db_table': 'recipe_components',
            },
        ),
    ]
