# Generated by Django 6.0.2 on 2026-03-21 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='output_quantity',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='Выпуск (количество)'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='output_unit_kind',
            field=models.CharField(blank=True, choices=[('naming', 'Наименование'), ('pieces', 'Штуки'), ('amount', 'Количество')], max_length=20, null=True, verbose_name='Тип учёта выпуска'),
        ),
    ]
