# Generated by Django 6.0.2 on 2026-05-03 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_recipecomponent_rework_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipecomponent',
            name='type',
            field=models.CharField(choices=[('raw', 'Сырьё'), ('chem', 'Хим. элемент'), ('rework_stock', 'Переделанные (склад)')], max_length=30, verbose_name='Тип'),
        ),
    ]
