# Generated by Django 4.2.30 on 2026-05-14 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_alter_recipecomponent_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='plasticprofile',
            name='weight_kg_per_piece',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True, verbose_name='Вес одной штуки, кг'),
        ),
    ]
